# TODO: Consider integrating this in a better way with the existing Dockerfile
tests:
  image: maven:3
  stop_signal: SIGKILL
  stdin_open: true
  tty: true
  working_dir: /workspace/app
  volumes:
    - ./:/workspace/app
    - /var/run/docker.sock:/var/run/docker.sock
    # Maven cache (optional)
    - ~/.m2:/root/.m2
  command: mvn test
