version: '3.7'

services:
  # API backend service
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - redis
    volumes:
      - /data/api

  # Client Service
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  # Redis Caching Service
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
