version: '3.7'

services:
  # API backend service
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - redis
      - db
    volumes:
      - /data/api

  # API notification service
  notification:
    build:
      context: notification-api
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    restart: always
    depends_on:
      - db
    volumes:
      - /data/notification-api

  # Client Service
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./client:/app

  # Redis Caching Service
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379

  # Database Service (H2)
  db:
    image: 1000kit/h2
    ports:
      - 8181:8181
      - 1521:1521
    volumes:
      - h2-data:/opt/h2-data

volumes:
  h2-data: