version: '3.7'

services:
  # API backend service
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - /data/api

  # Client Service
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: polls
      MYSQL_USER: callicoder
      MYSQL_PASSWORD: callicoder
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

  # Redis Caching Service
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

# Volumes
volumes:
  db-data: