logging:
  level:
    org.springframework.security: DEBUG
spring:
  session:
    store-type: redis
  datasource:
    url: jdbc:h2:tcp://localhost:1521/mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
zuul:
  routes:
    ui:
      url: http://localhost:8081
      sensitive-headers:
    admin:
      url: http://localhost:8082
      sensitive-headers:
    resource:
      url: http://localhost:9000
      sensitive-headers:
    coffee:
      url: http://localhost:9100
      sensitive-headers:

management:
  endpoints:
    web:
      exposure:
        include: httptrace
