logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
  ignored:
  - "*.bundle.*"
  - favicon.ico
spring:
  session:
    store-type: redis
  datasource:
    url: jdbc:h2:tcp://localhost:1521/mem:coffee
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
zuul:
  routes:
    ui:
      url: http://localhost:8081
      sensitive-headers:
    admin:
      url: http://localhost:8082
      sensitive-headers:
    resource:
      url: http://localhost:9000
      sensitive-headers:
    coffee:
      url: http://localhost:9100
      sensitive-headers:

management:
  endpoints:
    web:
      exposure:
        include: httptrace
