zuul:
  routes:
    notification-api:
      path: /notifications/**
      url: http://notification-api:9000
      sensitive-headers:

management:
  endpoints:
    web:
      exposure:
        include: httptrace
