server:
  port: 9093

spring:
  application:
    name: documentation-service
 
eureka:
  instance:
    appname: documentation-service
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

swagger: 
  config: 
    refreshrate: 5000

ribbon:
  eager-load:
    enabled: true

logging:
  level:
    web: DEBUG