version: '3.7'

# Define services
services:
  # Database Service (H2)
  db:
    image: 1000kit/h2
    ports:
      - "8181:8181"
      - "1521:1521"
    volumes:
      - h2-data:/opt/h2-data

  # Redis Caching Service
  redis:
    image: redis
    ports:
      - "6379:6379"

# Volumes
volumes:
  h2-data: