# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches:
      - dev
      - master

jobs:

  build:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.DATABASE_ROOT_PASSWORD}}
        ports:
          - 3306

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        DATABASE_USER: ${{secrets.DATABASE_USER}}
        DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        DATABASE_NAME: ${{secrets.DATABASE_NAME}}
        DATABASE_HOST: ${{secrets.DATABASE_HOST}}
        DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_HEADER: ${{ secrets.JWT_HEADER }}